project:
  type: website
  output-dir: docs
  resources:
    - /images/states/**
    - /material/**

website:
  title: "Advanced Modelling for Pharma"
  search: false
  page-footer:
    left: "Advanced Modelling for Pharma 2026, FLG Group"
    right:
      - icon: globe
        href: https://farma-unites.unige.ch/en/gervasio-lab/ 
      - icon: github
        href: https://github.com/Gervasiolab/
  navbar:
    background: dark
    left:
      - text: "Home"
        href: index.qmd
      - text: "Theory"
        menu:
          - text: "Introduction to Terminals"
            href: introduction_terminal.qmd
          - text: "Introduction to HPC"
            href: introduction_baobab.qmd
      - text: "Exam Exercises"
        menu:
          - text: "Adhesion GPCR"
            href: exercise_gpcr_stability.qmd
          - text: "Malaria target with ligands"
            href: exercise_malaria_targets.qmd
          - text: "mu-Opioid receptor"
            href: exercise_muOR_ligands.qmd
      - text: "Contacts"
        href: contacts.qmd

bibliography: includes/references.bib 

format:
  html:
    page-layout: full
    theme: spacelab
    css: styles.css
    code-fold: true
    toc: true
    toc-depth: 1
    
