project:
  type: website
  output-dir: docs

website:
  title: "Advanced Modelling for Pharma"
  search: false
  navbar:
    background: dark
    left:
      - text: "Home"
        href: index.qmd
      - text: "Tutorials"
        menu:
          - text: "Introduction to Terminals"
            href: introduction_terminal.qmd
          - text: "Introduction to HPC"
            href: introduction_baobab.qmd
      - text: "Exam Exercises"
        menu:
          - text: "Adhesion GPCR"
            href: exercise_gpcr_stability/exercise_gpcr_stability_index.qmd
          - text: "Malaria target with ligands"
            href: exercise_malaria_targets/exercise_malaria_targets_index.qmd
      - text: "Contacts"
        href: contacts.qmd

bibliography: includes/references.bib 

format:
  html:
    theme: spacelab
    css: styles.css
    include-in-header: includes/scripts.html
    code-fold: true
    toc: true
    toc-depth: 1
    
