---
title: "Investigate the dynamical stability a GPCR structure"
format:
  html:
    code-fold: true
---

{{< include /includes/exercise_stab_gpcr_nav.html >}}

## Generate the index file
The last passage before running the simulation is to generate and **index** file. This type of file is used to name part of the system by grouping the corresponding atom numbers under a given name. In this case, you need an index file because the thermostat is expecting two different groups to couple for temperature regulation, one that contains the protein and the lipids, which you will call `Protein_and_memb`, and one that contains the water and the ions, which you will call `Water_and_ions`. The reasons behind this are technical and go beyond the scope of this tutorial. However, the index file is a powerful tool to access only parts of the simulation box, and as such it is important to know how to generate one.

The command to generate and index file is `gmx make_ndx`. As input you should give the final configuration and call the output simply `index.ndx`, as in the following

```bash
gmx make_ndx -f start.gro -o index.ndx
```

GROMACS will answer by showing you what types of molecules it sees inside the box and which name it would give to them

```bash
  0 System              : 122863 atoms
  1 Protein             :  4440 atoms
  2 Protein-H           :  2187 atoms
  3 C-alpha             :   282 atoms
  4 Backbone            :   847 atoms
  5 MainChain           :  1129 atoms
  6 MainChain+Cb        :  1395 atoms
  7 MainChain+H         :  1407 atoms
  8 SideChain           :  3033 atoms
  9 SideChain-H         :  1058 atoms
 10 Prot-Masses         :  4440 atoms
 11 non-Protein         : 118423 atoms
 12 Other               : 42700 atoms
 13 CHL                 :  5180 atoms
 14 POPC                : 37520 atoms
 15 CL                  :     7 atoms
 16 Water               : 75716 atoms
 17 SOL                 : 75716 atoms
 18 non-Water           : 47147 atoms
 19 Ion                 :     7 atoms
 20 Water_and_ions      : 75723 atoms
```

A few of these groups are very important, e.g., group 1 is the protein, group 13 contains the cholesterol lipids while group 14 the POPC lipids, and so on. You can also see that GROMACS already puts together in a group water and ions (group 20, `Water_and_ions`). Thus, you will only need to generate another group that contains everything excluded water and ions, that is, the protein and the lipids. You can achieve this by typing

```bash
1 | 13 | 14
```

and pressing enter. You can read the legend at the end of the list of groups to understand what you just did. You basically said to take everything that is inside group 1 OR inside group 13 OR inside group 14, which means `Protein`, `CHL`, and `POPC` groups. If you press enter again, GROMACS will show the list of groups inside the index file, and you can see how now there is a new one at the end

```bash
[...]
 18 non-Water           : 47147 atoms
 19 Ion                 :     7 atoms
 20 Water_and_ions      : 75723 atoms
 21 Protein_CHL_POPC    : 47140 atoms
```

which is the union of the protein with the lipids. You can rename it by typing

```bash
name 21 Protein_and_memb
```

that is, take group 21 and rename it `Protein_and_memb`. Press enter again to confirm the command, and you will see now that the group changed name

```bash
[...]
 18 non-Water           : 47147 atoms
 19 Ion                 :     7 atoms
 20 Water_and_ions      : 75723 atoms
 21 Protein_and_memb    : 47140 atoms
```

You can exit the index generation by typing `q` and pressing enter. In your main directory you should now have the starting configuration `start.gro`, the corresponding topology `topol.top`, and the index file that you just generated, `index.ndx`. This is all what you need to run the following simulations. Each system directory reports also these files already prepared in the corresponding `solution_files` directory. You can compare the files that you obtained with those collected in this directory. Remember however that you can't mix the files. For example, let's suppose that you were able to obtain the `start.gro` initial configuration and the corresponding `topol.top` topology, but not the index file. You can't use the `index.ndx` file in the solution directory, as this was generated by using the `start.gro` file inside that same directory, which might have small differences in the water content. You should use all the files that have been generated one from the other to avoid inconsistencies.

<div class="nav-buttons">
  <a href="exercise_gpcr_stability_part_3.qmd" class="nav-btn prev-btn">&larr; Previous</a>
  <a href="exercise_gpcr_stability_index.qmd" class="nav-btn home-btn">Back to Beginning</a>
  <a href="exercise_gpcr_stability_part_5.qmd" class="nav-btn next-btn">Next &rarr;</a>
</div>