---
title: "Investigate the dynamical stability a GPCR structure"
format:
  html:
    code-fold: true
---

{{< include /includes/exercise_stab_gpcr_nav.html >}}

## A look into the starting files

First of all, start by downloading the exercise directories from the github repository.

<div class="download-buttons">
  <a href="https://github.com/obzehn/advanced_modelling_for_pharma/raw/main/docs/material/GPCR_structure_1_exercise.tar.gz" download="GPCR_structure_1_exercise.tar.gz" class="btn">Structure 1</a>
  <a href="https://github.com/obzehn/advanced_modelling_for_pharma/raw/main/docs/material/GPCR_structure_2_exercise.tar.gz" download="GPCR_structure_2_exercise.tar.gz" class="btn">Structure 2</a>
  <a href="https://github.com/obzehn/advanced_modelling_for_pharma/raw/main/docs/material/GPCR_structure_3_exercise.tar.gz" download="GPCR_structure_3_exercise.tar.gz" class="btn">Structure 3</a>
  <a href="https://github.com/obzehn/advanced_modelling_for_pharma/raw/main/docs/material/GPCR_structure_4_exercise.tar.gz" download="GPCR_structure_4_exercise.tar.gz" class="btn">Structure 4</a>
</div>

We provide four different structures. These are all different structures of the same adhesion protein in the same lipid bilayer. You should download and run simulations of at least two of them, so that you can compare the structures at the end of the molecular dynamics simulation. You can unzip the downloaded directories with the command

```bash
tar -xvf name_of_compressed_file.tar.gz
```

The individual directories of the different structures are organized as in the following

```bash
GPCR_structure_X_exercise
│   ionize.mdp
│   reference_topology_GPCR_structure_X.gro
│   reference_topology_GPCR_structure_X.top
│   sbatch_me.sh
│   water_removal.py
│
└─── forcefield
│   │   [various forcefields files]
│
└─── step1_em
│   │   em.mdp
│
└─── step2_nvt
│   │   [various nvt.mdp files]
│
└─── step3_npt
│   │   [various npt.mdp files]
│
└─── step4_prod
    │   prod.mdp
```

Going by order, you can see

- The `ionize.mdp`, `reference_topology_GPCR_structure_X.gro`, `reference_topology_GPCR_structure_X.top`, and `water_removal.py` files. These are the building blocks to set up your starting configuration. These will be covered in depth later in this tutorial;

- A `sbatch_me.sh` file. This is a text file that contains the set of instructions that will run your starting configuration through energy minimization, NVT, NPT, and eventually the production phase;

- A `forcefield` directory. Inside this, you can find several text files that define 'numerically' the key components of your system. You might recognize some of them, like `GPCR.itp`, `cholesterol.itp`, and `POPC.itp`. You can peek inside them and take a look at how a molecule is described numerically in MD simulations. The format of these files - that is, how these numbers are organized and reported - depends on the software you are using. Since in this course you use GROMACS, these files are written in GROMACS format. However, while these numbers and these files might be different for other softwares, the core idea of numerically representing with specific functions the intra- and inter-molecular interactions is paramount in molecular dynamics;

- The `step1_em`, `step2_nvt`, and `step3_npt` directories. Inside each of these you can find one or more `mdp` (molecular dynamics parameters) files that will be used to compile and run the energy minimization, the NVT, and the NPT equilibrations. These will be run sequentially by the script `sbatch_me.sh`, taking your starting configuration through a set of equilibration phases to relax the starting configuration gradually and avoid the system exploding;

- The `step4_prod` directory. Here there is the `prod.mdp` file, which is the final mdp file for the production run of the system. This is usually the longest part of the simulation, which can take 3 to 5 days on Baobab depending on the system. The final output files of the simulation will be inside this directory, and the analysis for the exam will mainly revolve around the `prod.xtc` trajectory file.

The idea of this tutorial is to give you the main ingredients to build your own solvated simulation box without going through the hassle of finding a good target to simulate, fix the experimental structure files, find a consistent force field to describe the system, and embedding the protein in the membrane. Considering this, inside the main directory you can find a copy of four files which will be the basic blocks to build the system, namely

- `ionize.mdp`, the mdp file to add the ions in the system;

- `reference_topology_GPCR_structure_X.gro`, the starting structure that contains the trans-membrane domain of the GPCR already embedded in the membrane;

- `reference_topology_GPCR_structure_X.top`, the starting topology of the system;

- `water_removal.py`, a python script that removes the water molecules that GROMACS wrongly positions within the lipid bilayer during the solvation phase.

From these, and if needed by using as reference the [Lysozyme in water](http://www.mdtutorials.com/gmx/lysozyme/) tutorial for solvation and ion addition, you should be able to obtain three files, that is the starting configuration of the solvated membrane, which you will name `start.gro`, the updated topology of the system, which you will name `topol.top`, and the index file of the system, which you will name `index.ndx`, which is a useful tool for better controlling complex multi-phase systems like a protein embedded in a lipid bilayer. These files will be then picked up by the `sbatch_me.sh` script and used as starting point to run the equilibration and the production runs of the system.

::: {.callout-note}
## Note

The rest of this tutorial will show the set-up of the simulation box by using as example the GPCR structure 1. Nevertheless, the logic of the procedure is identical and can be applied directly to all the other structures as well.

:::

<div class="nav-buttons">
  <a href="exercise_gpcr_stability_index.qmd" class="nav-btn prev-btn">&larr; Previous</a>
  <a href="exercise_gpcr_stability_index.qmd" class="nav-btn home-btn">Back to Beginning</a>
  <a href="exercise_gpcr_stability_part_2.qmd" class="nav-btn next-btn">Next &rarr;</a>
</div>
